# Generated by Django 3.2.16 on 2023-09-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='category',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_view_count', to='blog.post'),
            preserve_default=False,
        ),
    ]
